version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: property_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/property_db
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-web:/var/www/certbot
    ports:
      - "3000:3000"
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  db-data:
  certbot-web:
